# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Product.create(id:101,name:'Dope White',description:'DOPE Unisex White Preshrunk Cotton Tee',price:21,img_file:'dope_white',bullet_1:'S 15X24 inches / Chest 36-37 / Waist 29-31',bullet_2:'M 16x24 inches / Chest 38-40 / Waist 32-34',bullet_3:'L 18x24 inches / Chest 41-43 / Waist 35-37',bullet_4:'XL 19x24 inches / Chest 44-46 / Waist 38-40',bullet_5:'We do not accept returns if your purchased shirt does not fit.',bullet_6:'',shipping_cost:5)
Product.create(id:102,name:'Dope Grey',description:'DOPE Womenâ€™s Fitted Organic Preshrunk Cotton Grey Tee',price:21,img_file:'dope_grey',bullet_1:'XS 15x23 inches',bullet_2:'S 16x23 inches',bullet_3:'We do not accept returns if your purchased shirt does not fit.',bullet_4:'',bullet_5:'',bullet_6:'',shipping_cost:5)
Product.create(id:103,name:'Drake & 40 Black',description:'Drake Unisex Cotton Black Tee',price:21,img_file:'drake_black',bullet_1:'XS 18x23 inches',bullet_2:'S 19x23 inches',bullet_3:'M 20x24 inches',bullet_4:'L 21x25 inches',bullet_5:'XL 23x26 inches',bullet_6:'We do not accept returns if your purchased shirt does not fit.',shipping_cost:5)
Product.create(id:104,name:'Drake & 40 Navy',description:'Drake Womenâ€™s Fitted Organic Cotton Navy Tee',price:21,img_file:'drake_navy',bullet_1:'XS 15x22 inches',bullet_2:'S 17x22 inches',bullet_3:'L 20x25 inches',bullet_4:'We do not accept returns if your purchased shirt does not fit.',bullet_5:'',bullet_6:'',shipping_cost:5)
Product.create(id:105,name:'H-Town Vicious Black',description:'H-Town Vicious Womenâ€™s Cotton Fitted White Tee',price:21,img_file:'htown_vicious_black',bullet_1:'XS 14x21 inches',bullet_2:'S 15x21 inches',bullet_3:'M 16x21 inches',bullet_4:'L 17x22 inches',bullet_5:'XL 18x22 inches',bullet_6:'We do not accept returns if your purchased shirt does not fit',shipping_cost:5)
Product.create(id:106,name:'H-Town Vicious White',description:'H-Town Vicious Womenâ€™s Cotton Black Tee',price:16,img_file:'htown_vicious_white',bullet_1:'Size XS available only',bullet_2:'15x20 inches',bullet_3:'We do not accept returns if your purchased shirt does not fit.',bullet_4:'',bullet_5:'',bullet_6:'',shipping_cost:5)
Product.create(id:201,name:'Teal + Mint + Gold Bee Jewelry Dish',description:'Handmade Dish',price:9,img_file:'green_bee2',bullet_1:'4.25 inches in diameter',bullet_2:'Hand painted terra cotta',bullet_3:'Save the Bees!',bullet_4:'http://www.greenpeace.org/usa/sustainable-agriculture/save-the-bees/',bullet_5:'',bullet_6:'',shipping_cost:3)
Product.create(id:202,name:'Tan + Black + Gold Bee Jewelry Dish',description:'Handmade Dish',price:9,img_file:'tan_bee',bullet_1:'4.25 inches in diameter',bullet_2:'Hand painted terra cotta',bullet_3:'Save the Bees!',bullet_4:'http://www.greenpeace.org/usa/sustainable-agriculture/save-the-bees/',bullet_5:'',bullet_6:'',shipping_cost:3)
Product.create(id:203,name:'Blue + Gold Bee Jewelry Dish',description:'Handmade Dish',price:9,img_file:'blue_bee',bullet_1:'4.25 inches in diameter',bullet_2:'Hand painted terra cotta',bullet_3:'Save the Bees!',bullet_4:'http://www.greenpeace.org/usa/sustainable-agriculture/save-the-bees/',bullet_5:'',bullet_6:'',shipping_cost:3)
Product.create(id:301,name:'The Agatha',description:'Blue + Pink + Yellow Wooden Geometric Bead Necklace',price:11,img_file:'agatha',bullet_1:'Made out of wood and thus may vary in color',bullet_2:'Waxed cotton cord and faux leather clasp',bullet_3:'handle gently',bullet_4:'Packed in a gift box(Final Sale)',bullet_5:'',bullet_6:'',shipping_cost:3)
Product.create(id:302,name:'The Amaranthine',description:'Mint + Mink Wooden Geometric Bead Necklace',price:11,img_file:'amaranthine',bullet_1:'Made out of wood and thus may vary in color',bullet_2:'Waxed cotton cord and faux leather clasp',bullet_3:'Handle gently',bullet_4:'Packed in a gift box(Final Sale)',bullet_5:'',bullet_6:'',shipping_cost:3)
Product.create(id:303,name:'The Moss',description:'Teal + Pink + White Wooden Geometric Bead Necklace',price:11,img_file:'moss',bullet_1:'Made out of wood and thus may vary in color',bullet_2:'Waxed cotton cord and faux leather clasp',bullet_3:'Handle gently',bullet_4:'Packed in a gift box(Final Sale)',bullet_5:'',bullet_6:'',shipping_cost:3)
Product.create(id:304,name:'The Pacific',description:'Blue + Grey + Pink Wooden Geometric Bead Necklace',price:11,img_file:'pacific',bullet_1:'Made out of wood and thus may vary in color',bullet_2:'Waxed cotton cord and faux leather clasp',bullet_3:'Handle gently',bullet_4:'Packed in a gift box(Final Sale)',bullet_5:'',bullet_6:'',shipping_cost:3)
Product.create(id:305,name:'The Midnight',description:'Navy + Grey + White Wooden Geometric Bead Necklace',price:11,img_file:'midnight',bullet_1:'Made out of wood and thus may vary in color',bullet_2:'Waxed cotton rod and faux leather clasp',bullet_3:'Handle gently',bullet_4:'Packed in a gift box(Final Sale)',bullet_5:'',bullet_6:'',shipping_cost:3)
Product.create(id:306,name:'The Cavalcanti',description:'Mint + Yellow + Grey Wooden Geometric Bead Necklace',price:11,img_file:'cavalcanti',bullet_1:'Made out of wood and thus may vary in color',bullet_2:'Waxed cotton cord and faux leather clasp',bullet_3:'Handle gently',bullet_4:'Packed in a gift box(Final Sale)',bullet_5:'',bullet_6:'',shipping_cost:3)
Product.create(id:307,name:'The Wes',description:'Yellow Wood Earrings',price:9.5,img_file:'wes',bullet_1:'Made out of wood and thus may vary in color',bullet_2:'High quality surgical steel posts: nickel free',bullet_3:'Although the earrings are coated with a clear matte varnish they should be taken off before going under water and showering(Handle gently)',bullet_4:'Packed in gift box (Final Sale)',bullet_5:'',bullet_6:'',shipping_cost:3)
Product.create(id:308,name:'The Satellite',description:'Black Wood Earrings',price:9.5,img_file:'satellite',bullet_1:'Made out of wood and thus may vary in color',bullet_2:'High quality surgical steel posts: nickel free',bullet_3:'Although the earrings are coated with a clear matte varnish they should be taken off before going under water and showering(Handle gently)',bullet_4:'Packed in gift box (Final Sale)',bullet_5:'',bullet_6:'',shipping_cost:3)
Product.create(id:309,name:'The Suzy',description:'Yellow and Turquoise Wood Earrings',price:9.5,img_file:'suzy',bullet_1:'Made out of wood and thus may vary in color',bullet_2:'High quality surgical steel posts: nickel free',bullet_3:'Although the earrings are coated with a clear matte varnish they should be taken off before going under water and showering(Handle gently)',bullet_4:'Packed in gift box (Final Sale)',bullet_5:'',bullet_6:'',shipping_cost:3)
Product.create(id:310,name:'The Margot',description:'Navy and Light Pink Wood Earrings',price:9.5,img_file:'margot',bullet_1:'Made out of wood and thus may vary in color',bullet_2:'High quality surgical steel posts: nickel free',bullet_3:'Although the earrings are coated with a clear matte varnish they should be taken off before going under water and showering(Handle gently)',bullet_4:'Packed in gift box (Final Sale)',bullet_5:'',bullet_6:'',shipping_cost:3)
Product.create(id:311,name:'The Verda',description:'Teal Wood Earrings',price:9.5,img_file:'verda',bullet_1:'Made out of wood and thus may vary in color',bullet_2:'High quality surgical steel posts: nickel free',bullet_3:'Although the earrings are coated with a clear matte varnish they should be taken off before going under water and showering(Handle gently)',bullet_4:'Packed in gift box (Final Sale)',bullet_5:'',bullet_6:'',shipping_cost:3)
